### ISSUE TITLE
As an urban city planner, I need a list of all the capital cities in a region organised by largest to smallest to assist with the development of housing.

### ISSUE THREAD

**Issue by RyanConnor6** [JackCameron45/group14-sem-coursework#19]
SELECT city.name, city.Population FROM city, country
 WHERE  city.CountryCode = country.Code
 AND  city.ID IN 
 (SELECT country.Capital FROM country 
  WHERE country.Region = "Polynesia")
 ORDER BY city.Population DESC;

**Comment by MichalBoduch** [comment]
SQL query needs to be created to extract described data from database
