### ISSUE TITLE
As an urban city planner, I need a list of the top N populated capital cities in a continent where N is provided by the user to assist with the development of housing.

### ISSUE THREAD

**Issue by RyanConnor6** [JackCameron45/group14-sem-coursework#21]
SELECT city.name, city.Population FROM city, country
 WHERE  city.CountryCode = country.Code
 AND  city.ID IN 
 (SELECT country.Capital FROM country 
  WHERE country.Continent = "Europe")
 ORDER BY city.Population DESC
LIMIT 5;

**Comment by MichalBoduch** [comment]
SQL query needs to be created to extract described data from database
