### ISSUE TITLE
As an urban city planner, I need a list of the population of people, people living in cities, and people not living in cities in each region to assist with the development of housing.

### ISSUE THREAD

**Issue by RyanConnor6** [JackCameron45/group14-sem-coursework#24]
SELECT co.Region, SUM((SELECT sum(ci.Population) FROM city ci  WHERE ci.CountryCode = co.Code )) AS Cities_Population, 
        SUM(co.Population) - SUM((SELECT sum(ci.Population) FROM city ci  WHERE ci.CountryCode = co.Code )) AS Rural_Population
FROM country co
GROUP BY co.Region
ORDER BY co.Region ASC;

**Comment by MichalBoduch** [comment]
SQL query needs to be created to extract described data from database
