### ISSUE TITLE
As an urban city planner, I need a list of the population of people, people living in cities, and people not living in cities in each country to assist with the development of housing.

### ISSUE THREAD

**Issue by RyanConnor6** [JackCameron45/group14-sem-coursework#25]
SELECT country.Name, SUM(city.Population) AS Cities_Population, 
          country.Population-SUM(city.Population) AS Rural_Population
  FROM city, country
 WHERE  city.CountryCode = country.Code
 GROUP BY country.Code
 ORDER BY country.Name;

**Comment by MichalBoduch** [comment]
SQL query needs to be created to extract described data from database
