### ISSUE TITLE
As a Java application developer I need to create a capital Capital City Report. A capital city report requires the following columns: Name, Country, Population to aid with the localization of my project.

### ISSUE THREAD

**Issue by RyanConnor6** [JackCameron45/group14-sem-coursework#32]
SELECT city.Name, country.Name AS Country, city.Population
FROM country, city
WHERE city.ID = country.Capital
AND city.Name = "London";

**Comment by MichalBoduch** [comment]
SQL query needs to be created to extract described data from database
