### ISSUE TITLE
As a Java application developer I need to show the number of people who speak the following languages from greatest number to smallest, including the percentage of the world population: Chinese. English. Hindi. Spanish. Arabic. to aid with the localization of my project.

### ISSUE THREAD

**Issue by RyanConnor6** [JackCameron45/group14-sem-coursework#33]
SELECT countrylanguage.Language, SUM(country.Population) AS Population,
    FORMAT((SUM(country.Population)/(SELECT SUM(country.Population) AS World_Population
  FROM  country))*100,2)  AS "Percentage of The World Population" 
FROM country, countrylanguage
WHERE  country.Code = countrylanguage.CountryCode
 AND countrylanguage.Language 
           IN ("Chinese", "English", "Hindi", "Spanish", "Arabic")
GROUP BY countrylanguage.Language
ORDER BY Population DESC;

**Comment by MichalBoduch** [comment]
SQL query needs to be created to extract described data from database
