### ISSUE TITLE
As a Java application developer I need to show the population of people living in cities, and people not living in cities in each continent.
 to aid with the localization of my project.

### ISSUE THREAD

**Issue by RyanConnor6** [JackCameron45/group14-sem-coursework#34]
SELECT co.Continent, SUM((SELECT sum(ci.Population) FROM city ci  WHERE ci.CountryCode = co.Code )) AS Cities_Population, 
        SUM(co.Population) - SUM((SELECT sum(ci.Population) FROM city ci  WHERE ci.CountryCode = co.Code )) AS Rural_Population
FROM country co
GROUP BY co.Continent
ORDER BY co.Continent ASC;

**Comment by MichalBoduch** [comment]
SQL query needs to be created to extract described data from database
