### ISSUE TITLE
As a Java application developer I need to create Population reports, the following information is requested: The name of the continent/region/country. The total population of the continent/region/country. The total population of the continent/region/country living in cities (including a %). The total population of the continent/region/country not living in cities (including a %).  to aid with the localization of my project.

### ISSUE THREAD

**Issue by RyanConnor6** [JackCameron45/group14-sem-coursework#36]
SELECT co.Continent, SUM((SELECT sum(ci.Population) FROM city ci  WHERE ci.CountryCode = co.Code )) AS Cities_Population, 
   SUM(co.Population) - SUM((SELECT sum(ci.Population) FROM city ci  WHERE ci.CountryCode = co.Code )) AS Rural_Population,
   FORMAT(SUM((SELECT sum(ci.Population) FROM city ci  WHERE ci.CountryCode = co.Code )) 
	/(SUM(co.Population) ) *100,2) AS Percentage_Living_in_Cities,
   FORMAT(100-(SUM((SELECT SUM(ci.Population) FROM city ci  WHERE ci.CountryCode = co.Code )) 
	/(SUM(co.Population) ))*100,2) AS Percentage_Living_in_Rural_Areas
FROM country co
GROUP BY co.Continent
ORDER BY co.Continent ASC;

**Comment by MichalBoduch** [comment]
sql

**Comment by MichalBoduch** [comment]
SQL query needs to be created to extract described data from database
