### ISSUE TITLE
As a population data analyst, I need a list of the top N populated countries in the world where N is provided by the user to aid with statistics.

### ISSUE THREAD

**Issue by RyanConnor6** [JackCameron45/group14-sem-coursework#4]
SELECT country.name, country.Population FROM country
  ORDER BY country.Population DESC
  LIMIT 5;

**Comment by MichalBoduch** [comment]
SQL query needs to be created to extract described data from database

**Comment by MichalBoduch** [comment]
SQL query needs to be created to extract described data from database
